name: Update Downloads Count JSON

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar jq
        run: sudo apt-get install -y jq

      - name: Descargar releases desde GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/iArtie/DarkModeV4-Index/releases \
            > releases.json

      - name: Generar downloadscount.json desde texturepacks.json
        run: |
          if [ ! -f texturepacks.json ]; then
            echo "{}" > texturepacks.json
          fi

          echo "{}" > downloadscount.json

          mapfile -t modes < <(jq -r 'keys[]' texturepacks.json)

          for mode in "${modes[@]}"; do
            has_lastest=$(jq -r --arg mode "$mode" '.[$mode] | has("Lastest")' texturepacks.json)
            if [[ "$has_lastest" == "true" ]]; then
              version=$(jq -r --arg mode "$mode" '.[$mode].Lastest.version' texturepacks.json)
              download_url=$(jq -r --arg mode "$mode" '.[$mode].Lastest.download' texturepacks.json)

              count=$(jq --arg url "$download_url" -r '
                .[] | .assets[]? | select(.browser_download_url == $url) | .download_count // 0
              ' releases.json)

              if [[ -n "$count" ]]; then
                jq --arg mode "$mode" --arg version "$version" --arg url "$download_url" --argjson count "$count" \
                  '. + {($mode): {($version): { "download link": $url, "download count": $count }}}' \
                  downloadscount.json > tmp.json && mv tmp.json downloadscount.json
              fi
            fi
          done

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add downloadscount.json

          if ! git diff --cached --quiet; then
            git commit -m "Update downloadscount.json from texturepacks.json"
            git push
          else
            echo "No changes to commit."
          fi
# Active workflow
