name: Update Texture Packs JSON

on:
  issues:
    types: [opened]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if the user is a contributor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener el nombre de usuario del creador de la issue
          ISSUE_AUTHOR=${{ github.event.issue.user.login }}
          REPO_OWNER=${{ github.repository_owner }}
          
          # Comprobar si el autor de la issue ha realizado contribuciones al repositorio
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/${{ github.repository }}/commits?author=$ISSUE_AUTHOR")

          # Si la respuesta es 200, significa que ha realizado commits y es un contributor
          if [ "$response" != "200" ]; then
            echo "Error: $ISSUE_AUTHOR is not a contributor of the repository."
            exit 1
          fi

      - name: Extract issue parameters and update JSON
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Imprimir el contenido de la issue para depurar
          echo "ISSUE BODY: $ISSUE_BODY"

          # Extraer parámetros del cuerpo de la issue, usando líneas específicas
          TYPE=$(echo "$ISSUE_BODY" | sed -n '3p' | xargs)  # La línea 2 después de "### TexturePack Type"
          VERSION=$(echo "$ISSUE_BODY" | sed -n '7p' | xargs)  # La línea 4 después de "### Version"
          DOWNLOAD=$(echo "$ISSUE_BODY" | sed -n '11p' | xargs)  # La línea 6 después de "### Download Link"

          # Imprimir los valores extraídos para depurar
          echo "TYPE: $TYPE"
          echo "VERSION: $VERSION"
          echo "DOWNLOAD: $DOWNLOAD"

          # Comprobar si los valores están vacíos
          if [[ -z "$TYPE" || -z "$VERSION" || -z "$DOWNLOAD" ]]; then
            echo "Error: Missing parameters. Type, Version, and Download are required."
            exit 1
          fi

          # Leer y actualizar el archivo JSON
          JSON_FILE="texturepacks.json"
          UPDATED_JSON=$(jq --arg type "$TYPE" --arg version "$VERSION" --arg download "$DOWNLOAD" \
            '.[$type][$version] = { download: $download }' "$JSON_FILE")

          # Sobreescribir el archivo
          echo "$UPDATED_JSON" > "$JSON_FILE"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add texturepacks.json
          git commit -m "Update texturepacks.json from issue #${{ github.event.issue.number }}"
          git push

      - name: Close the issue after successful update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
