name: Update Texture Packs JSON

on:
  issues:
    types: [opened]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if the user is iArtie or GhostPower13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtener el nombre de usuario del creador de la issue
          ISSUE_AUTHOR=${{ github.event.issue.user.login }}
          
          # Comprobar si el autor es iArtie o GhostPower13
          if [[ "$ISSUE_AUTHOR" != "iArtie" && "$ISSUE_AUTHOR" != "GhostPower13" ]]; then
            echo "Error: $ISSUE_AUTHOR is not authorized to trigger this action."
            exit 1
          fi

      - name: Extract issue parameters and update JSON
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Imprimir el contenido de la issue para depurar
          echo "ISSUE BODY: $ISSUE_BODY"

          # Extraer parámetros del cuerpo de la issue, usando líneas específicas
          TYPE=$(echo "$ISSUE_BODY" | sed -n '3p' | xargs)  # La línea 2 después de "### TexturePack Type"
          VERSION=$(echo "$ISSUE_BODY" | sed -n '7p' | xargs)  # La línea 4 después de "### Version"
          DOWNLOAD=$(echo "$ISSUE_BODY" | sed -n '11p' | xargs)  # La línea 6 después de "### Download Link"

          # Imprimir los valores extraídos para depurar
          echo "TYPE: $TYPE"
          echo "VERSION: $VERSION"
          echo "DOWNLOAD: $DOWNLOAD"

          # Comprobar si los valores están vacíos
          if [[ -z "$TYPE" || -z "$VERSION" || -z "$DOWNLOAD" ]]; then
            echo "Error: Missing parameters. Type, Version, and Download are required."
            exit 1
          fi

          # Leer el archivo JSON existente
          JSON_FILE="texturepacks.json"
          JSON_CONTENT=$(cat "$JSON_FILE")

          # Asegurarse de que el tipo exista, si no, lo creamos
          if ! echo "$JSON_CONTENT" | jq -e ".\"$TYPE\"" > /dev/null; then
            JSON_CONTENT=$(echo "$JSON_CONTENT" | jq --arg type "$TYPE" '. + {($type): {}}')
          fi

          # Agregar la nueva versión al tipo especificado
          UPDATED_JSON=$(echo "$JSON_CONTENT" | jq --arg type "$TYPE" --arg version "$VERSION" --arg download "$DOWNLOAD" '
            .[$type][$version] = { "download": $download }')

          # Actualizar la versión Lastest con la misma URL de descarga
          UPDATED_JSON=$(echo "$UPDATED_JSON" | jq --arg type "$TYPE" --arg version "$VERSION" --arg download "$DOWNLOAD" '
            .[$type]["Lastest"] = { "download": $download }')

          # Mover la clave "Lastest" al final de las versiones
          UPDATED_JSON=$(echo "$UPDATED_JSON" | jq '
            .["METAL"] |= 
              with_entries(
                if .key == "Lastest" then
                  . 
                else 
                  { .key, .value }
                end
              ) | 
            .[$type]["Lastest"] |= { "download": $download }
          ')

          # Sobreescribir el archivo con los cambios
          echo "$UPDATED_JSON" > "$JSON_FILE"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add texturepacks.json
          git commit -m "Update texturepacks.json from issue #${{ github.event.issue.number }}"
          git push

      - name: Close the issue after successful update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"state": "closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
